 export const users = [
 {
   id: 1,
   name: "Noah Thompson",
   description: "Product Designer who focuses on simplicity & usability.",
   coverImg: "https://picsum.photos/800/300?random=1",
   avatar: "https://i.pravatar.cc/150?img=11",
   exp: 75,
   stats: {
     likes: 72900,
     posts: 828,
     views: 342900,
   },
 },
 {
   id: 2,
   name: "Emma Wilson",
   description: "UX Researcher passionate about user behavior and empathy.",
   coverImg: "https://picsum.photos/800/300?random=2",
   avatar: "https://i.pravatar.cc/150?img=12",
   exp: 68,
   stats: {
     likes: 51400,
     posts: 412,
     views: 198300,
   },
 },
 {
   id: 3,
   name: "Liam Carter",
   description: "Frontend Developer crafting clean and scalable UI.",
   coverImg: "https://picsum.photos/800/300?random=3",
   avatar: "https://i.pravatar.cc/150?img=13",
   exp: 82,
   stats: {
     likes: 88300,
     posts: 965,
     views: 410200,
   },
 },
 {
   id: 4,
   name: "Sophia Martinez",
   description: "Visual Designer with a love for minimal aesthetics.",
   coverImg: "https://picsum.photos/800/300?random=4",
   avatar: "https://i.pravatar.cc/150?img=14",
   exp: 70,
   stats: {
     likes: 46300,
     posts: 389,
     views: 176900,
   },
 },
 {
   id: 5,
   name: "James Anderson",
   description: "Mobile App Designer focusing on smooth interactions.",
   coverImg: "https://picsum.photos/800/300?random=5",
   avatar: "https://i.pravatar.cc/150?img=15",
   exp: 77,
   stats: {
     likes: 65400,
     posts: 540,
     views: 289400,
   },
 },
 {
   id: 6,
   name: "Olivia Brown",
   description: "Content Creator sharing design tips and workflows.",
   coverImg: "https://picsum.photos/800/300?random=6",
   avatar: "https://i.pravatar.cc/150?img=16",
   exp: 64,
   stats: {
     likes: 39200,
     posts: 271,
     views: 154600,
   },
 },
 {
   id: 7,
   name: "William Lee",
   description: "Full Stack Developer with a design-first mindset.",
   coverImg: "https://picsum.photos/800/300?random=7",
   avatar: "https://i.pravatar.cc/150?img=17",
   exp: 85,
   stats: {
     likes: 94700,
     posts: 1103,
     views: 512800,
   },
 },
 {
   id: 8,
   name: "Ava Johnson",
   description: "UI Designer crafting modern and accessible interfaces.",
   coverImg: "https://picsum.photos/800/300?random=8",
   avatar: "https://i.pravatar.cc/150?img=18",
   exp: 72,
   stats: {
     likes: 57800,
     posts: 467,
     views: 243100,
   },
 },
 {
   id: 9,
   name: "Benjamin Clark",
   description: "Design Lead mentoring teams and building systems.",
   coverImg: "https://picsum.photos/800/300?random=9",
   avatar: "https://i.pravatar.cc/150?img=19",
   exp: 90,
   stats: {
     likes: 112400,
     posts: 1320,
     views: 689300,
   },
 },
 {
   id: 10,
   name: "Mia Rodriguez",
   description: "Creative Designer blending illustration and UI.",
   coverImg: "https://picsum.photos/800/300?random=10",
   avatar: "https://i.pravatar.cc/150?img=20",
   exp: 66,
   stats: {
     likes: 44100,
     posts: 356,
     views: 187500,
   },
 },
]